# Generated by Django 4.1 on 2024-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="部门描述"),
        ),
    ]
