# Generated by Django 4.1 on 2024-06-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems", "0003_department_employee_salary_employee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="department",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="employee",
        ),
        migrations.AddField(
            model_name="attendance",
            name="employee_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="员工ID"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="姓名"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="manager_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="部门管理员ID"),
        ),
        migrations.AddField(
            model_name="department",
            name="manager_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="部门管理员"
            ),
        ),
        migrations.AddField(
            model_name="salary",
            name="employee_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="员工ID"),
        ),
        migrations.AddField(
            model_name="salary",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="姓名"
            ),
        ),
    ]
