# Generated by Django 4.1 on 2024-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ems", "0004_remove_attendance_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="部门"
            ),
        ),
    ]
